### ISSUE TITLE
bad histogram datafile prevents entire output from generating

### ISSUE THREAD

**Issue by bloer** [bloer/bgexplorer#53]
2020-11-06 16:50:45,353 - bgexplorer - ERROR - Exception on /explore/CUTER14_BL/HEAD/getspectrum/PD2 multiples [GET]
Traceback (most recent call last):
  File "/srv/bgexplorer/instances/bgexplorer-cute/virtenv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/bgexplorer/instances/bgexplorer-cute/virtenv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/bgexplorer/instances/bgexplorer-cute/virtenv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/bgexplorer/instances/bgexplorer-cute/virtenv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/srv/bgexplorer/instances/bgexplorer-cute/virtenv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/bgexplorer/instances/bgexplorer-cute/virtenv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/bgexplorer/instances/bgexplorer-cute/virtenv/lib64/python3.6/site-packages/bgexplorer/modelviewer/modelviewer.py", line 343, in getspectrum
    spectrum = self.simsdb.evaluate([speceval], matches)[0]
  File "/srv/bgexplorer/instances/bgexplorer-cute/virtenv/lib64/python3.6/site-packages/bgmodelbuilder/simulationsdb/mongosimsdb.py", line 139, in evaluate
    val = v.norm(v.parse(doc, match), match)
  File "/srv/bgexplorer/instances/bgexplorer-cute/app.py", line 159, in parse
    hc = self.hits.parse(doc, match) / self.hits.scale
  File "/srv/bgexplorer/instances/bgexplorer-cute/virtenv/lib64/python3.6/site-packages/bgmodelbuilder/simulationsdb/simdoceval.py", line 271, in parse
    hist = np.zeros_like(bin_edges[:-1])
TypeError: 'NoneType' object is not subscriptable

**Comment by bloer** [comment]
fixed in 0.5.3
