### ISSUE TITLE
NoneType comparison causing Internal Server Error when on queries page

### ISSUE THREAD

**Issue by SimonHarms** [bloer/bgexplorer#77]
Loading at the queries overview page causes an internal server error with the following stacktrace in the server console:

```
Traceback (most recent call last):
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/bgexplorer/modelviewer/modelviewer.py", line 236, in queriesoverview
    return render_template('queriesoverview.html', queries=queries)
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/bgexplorer/modelviewer/templates/queriesoverview.html", line 3, in top-level template code
    {% from "macros.html" import printdataset %}
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/bgexplorer/modelviewer/templates/modelbase.html", line 3, in top-level template code
    {% set longname = g.model.name + " v" + g.model.version %}
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/bgexplorer/templates/base.html", line 23, in top-level template code
    {% block doc -%}
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/bgexplorer/templates/base.html", line 26, in block 'doc'
    {%- block html %}
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/bgexplorer/templates/base.html", line 74, in block 'html'
    {% block body -%}
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/bgexplorer/templates/base.html", line 112, in block 'body'
    {% block content -%}
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/bgexplorer/templates/base.html", line 123, in block 'content'
    <div id="pagecontent" class="clearfix" >{% block pagecontent %}{% endblock %}</div>
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/bgexplorer/modelviewer/templates/queriesoverview.html", line 34, in block 'pagecontent'
    <td>{% for dataset, matches in matches | groupby('dataset') %}{{ printdataset(dataset) }}{% endfor %}</td>
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/jinja2/async_utils.py", line 45, in wrapper
    return normal_func(*args, **kwargs)
  File "/data/bgexplorer/cute/bgexplorer-cute/virtenv/lib/python3.10/site-packages/jinja2/filters.py", line 1233, in sync_do_groupby
    for key, values in groupby(sorted(value, key=expr), expr)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

I believe the issue is that since there's query matches that don't have datasets associated with them when it tries to make links to the datasets, which it does by using the filter `groupy('dataset')` and then taking the dataset associated with each group, it ends up comparing NoneTypes during sorting. In my testing adding the filter `rejectattr('dataset', 'none')` to line 34 in queriesoverview.html so it reads ` <td>{% for dataset, matches in matches | rejectattr('dataset', 'none') | groupby('dataset') %}{{ printdataset(dataset) }}{% endfor %}</td>` fixed the issue by leaving out matches that don't have a dataset attached when doing the grouping.

The server was using the bgexplorer-cute implementation here but it looks like this is a general issue with bgexplorer. You can look at the models on the server here: http://206.12.97.188:5000

I know Tyler Martin was working on a fix for the query overviews page but it looks like he was trying to solve a different issue so I don't believe this issue has been reported here yet.

**Comment by bloer** [comment]
this has been fixed on 0.7.4
